//! Interactive setup wizard for `penne --config` (no value), mirroring
//! `pesto`'s `ui::wizard` — same prompt-driven flow, scaled down to what
//! `penne`'s config actually has (servers + a download directory, no
//! posting-only fields).

use std::io::{self, Write};

use anyhow::{Context, Result};

use crate::config;

/// Run the interactive setup wizard, writing the result to
/// [`config::default_config_path`].
pub fn run() -> Result<()> {
    let path = config::default_config_path()
        .context("cannot locate a config directory: set $HOME or $XDG_CONFIG_HOME")?;

    println!("penne setup — answer a few questions to create your config.");
    println!("Press Enter to accept the [default] shown in brackets.\n");

    if path.exists() {
        let overwrite = ask("Config already exists; overwrite it? (y/N)", "n")?;
        if !overwrite.eq_ignore_ascii_case("y") {
            println!("Aborted; existing config kept.");
            return Ok(());
        }
    }

    let host = ask_required("NNTP server hostname")?;
    let port: u16 = ask_number("Server port", 563)?;
    let ssl = ask("Use TLS? (Y/n)", "y")?;
    let ssl = !ssl.eq_ignore_ascii_case("n");
    let connections: usize = ask_number("Parallel connections", 8)?;
    let username = ask("Username (blank for none)", "")?;
    let password = if username.is_empty() {
        String::new()
    } else {
        ask("Password", "")?
    };
    let download_dir = ask("Download directory", "./downloads")?;
    let retries: u32 = ask_number("Retry attempts per segment", 3)?;

    let mut toml = String::new();
    toml.push_str("# penne configuration — generated by `penne --config`.\n\n");
    toml.push_str(&format!("download_dir = \"{}\"\n", esc(&download_dir)));
    toml.push_str(&format!("retries = {retries}\n\n"));

    toml.push_str("[[servers]]\n");
    toml.push_str(&format!("host = \"{}\"\n", esc(&host)));
    toml.push_str(&format!("port = {port}\n"));
    toml.push_str(&format!("ssl = {ssl}\n"));
    toml.push_str(&format!("connections = {connections}\n"));
    if !username.is_empty() {
        toml.push_str(&format!("username = \"{}\"\n", esc(&username)));
        toml.push_str(&format!("password = \"{}\"\n", esc(&password)));
    }
    toml.push_str(
        "# A second [[servers]] entry is a backup provider, tried only for\n\
         # segments the first one didn't have — add one by hand if you use one.\n",
    );

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating config directory `{}`", parent.display()))?;
    }
    std::fs::write(&path, toml)
        .with_context(|| format!("writing config file `{}`", path.display()))?;

    println!("\nWrote {}", path.display());
    println!("penne will load it automatically. Download with: penne download <FILE.nzb>");
    Ok(())
}

fn ask(label: &str, default: &str) -> Result<String> {
    if default.is_empty() {
        print!("{label}: ");
    } else {
        print!("{label} [{default}]: ");
    }
    io::stdout().flush().ok();
    let mut line = String::new();
    io::stdin()
        .read_line(&mut line)
        .context("reading from stdin")?;
    let line = line.trim().to_string();
    Ok(if line.is_empty() {
        default.to_string()
    } else {
        line
    })
}

fn ask_required(label: &str) -> Result<String> {
    loop {
        let value = ask(label, "")?;
        if !value.is_empty() {
            return Ok(value);
        }
        println!("  (required — please enter a value)");
    }
}

/// Like [`ask`], but re-prompts until the answer parses as `T` instead of
/// accepting anything and writing it unquoted into the generated TOML —
/// bad input would otherwise produce a config file that fails to parse the
/// next time `penne` loads it, with no chance to notice until then.
fn ask_number<T: std::str::FromStr + std::fmt::Display>(label: &str, default: T) -> Result<T> {
    loop {
        let raw = ask(label, &default.to_string())?;
        match raw.trim().parse() {
            Ok(value) => return Ok(value),
            Err(_) => println!("  (not a valid number — please try again)"),
        }
    }
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
