#!/usr/bin/env bash
# bench/lib/data.sh — workload definitions and the corpus they materialise.
#
# A workload is a declarative description of a real upload: which files, how
# big, how compressible, and the posting settings that go with it. Adding one
# is dropping a file into bench/workloads/ — no code changes anywhere.
#
# Corpora are generated by `bench-gen` from a fixed seed, cached under
# bench/data/, and verified by CRC-32 against a manifest. That combination is
# what makes a result comparable between two machines: same seed and same
# scale means the same bytes, and the manifest proves it rather than assuming
# it. Regenerating tens of GB on every run would otherwise dominate the
# suite's own wall-clock time.

# Scale factor applied to every size in a workload, so the same definitions
# work on a laptop and on a 128-core server. Recorded in the corpus directory
# name, so two scales never share a cache entry or a result row.
BENCH_SCALE="${BENCH_SCALE:-1.0}"

# scaled_size <size_spec> — apply BENCH_SCALE, round to a 4 KiB boundary.
# Rounding matters: PAR2 slice sizes must be a multiple of 4, and an unaligned
# corpus adds a ragged final slice that differs between scales.
scaled_size() {
    local spec=$1
    awk -v s="$spec" -v scale="$BENCH_SCALE" 'BEGIN {
        n = s + 0
        unit = toupper(substr(s, length(n "") + 1, 1))
        mult = 1
        if (unit == "K") mult = 1024
        else if (unit == "M") mult = 1048576
        else if (unit == "G") mult = 1073741824
        else if (unit == "T") mult = 1099511627776
        bytes = int(n * mult * scale)
        if (bytes < 4096) bytes = 4096
        printf "%d", int(bytes / 4096) * 4096
    }'
}

workload_file() { echo "$BENCH_DIR/workloads/$1.workload"; }

workload_list() {
    local f
    for f in "$BENCH_DIR"/workloads/*.workload; do
        [[ -e $f ]] || continue
        basename "$f" .workload
    done
}

# workload_load <name> — source the definition, applying defaults.
workload_load() {
    local name=$1 file
    file=$(workload_file "$name")
    [[ -r $file ]] || die "unknown workload '$name' (see bench/workloads/)"

    # Defaults, reset per load so a workload that omits a field never inherits
    # the previous one's value.
    WL_NAME=$name
    WL_DESC=""
    WL_FILES=()
    WL_GENSETS=()
    WL_SEED=1
    WL_PAR2_PCT=10
    WL_ARTICLE_SIZE=768000
    WL_COMPRESS=""
    WL_COMPRESS_VOLUME=""
    WL_OBFUSCATE=none
    WL_LAYERS="stages e2e"
    WL_CONNECTIONS=8
    # quick (<3 GiB total) / standard (tens of GiB) / heavy (opt-in only).
    # Tiers exist so `run.sh` can do something useful on a laptop without
    # generating a corpus larger than the disk.
    WL_TIER=standard
    WL_NOTE=""

    # shellcheck disable=SC1090
    source "$file"
    [[ ${#WL_FILES[@]} -gt 0 || ${#WL_GENSETS[@]} -gt 0 ]] ||
        die "workload '$name' defines no files"
}

# workload_dir <name> — where this workload's corpus lives.
workload_dir() { echo "$BENCH_DATA_DIR/$1@${BENCH_SCALE}"; }

# workload_materialise <name> — generate (or reuse) the corpus. Prints the
# corpus directory on stdout; progress goes to stderr so the caller can
# capture the path.
workload_materialise() {
    local name=$1
    workload_load "$name"
    local dir manifest
    dir=$(workload_dir "$name")
    manifest="$dir/.manifest.jsonl"
    mkdir -p "$dir"

    local tmp_manifest="$manifest.tmp"
    : > "$tmp_manifest"

    local entry rel size entropy path
    for entry in "${WL_FILES[@]}"; do
        IFS='|' read -r rel size entropy <<< "$entry"
        path="$dir/$rel"
        mkdir -p "$(dirname "$path")"
        "$BENCH_GEN_BIN" --out "$path" \
            --size "$(scaled_size "$size")" \
            --seed "$(( WL_SEED + ${#rel} ))" \
            --entropy "${entropy:-100}" >> "$tmp_manifest" ||
            die "bench-gen failed for $rel"
    done

    local subdir template count
    for entry in "${WL_GENSETS[@]}"; do
        IFS='|' read -r subdir template count size entropy <<< "$entry"
        mkdir -p "$dir/$subdir"
        "$BENCH_GEN_BIN" --out-dir "$dir/$subdir" \
            --template "$template" --count "$count" \
            --size "$(scaled_size "$size")" \
            --seed "$(( WL_SEED + count ))" \
            --entropy "${entropy:-100}" >> "$tmp_manifest" ||
            die "bench-gen failed for genset $subdir/$template"
    done

    mv "$tmp_manifest" "$manifest"
    echo "$dir"
}

# workload_bytes <name> — total input size of the materialised corpus.
#
# Excludes `*.par2`: the PAR2 suite writes recovery sets next to the data (the
# only place every tool can verify and repair from), and counting those as
# input would inflate the corpus size, the geometry and every throughput
# figure derived from them.
workload_bytes() {
    local dir
    dir=$(workload_dir "$1")
    [[ -d $dir ]] || { echo 0; return; }
    find "$dir" -type f ! -name '.manifest.jsonl' ! -name '*.par2' \
        -printf '%s\n' 2>/dev/null |
        awk '{ s += $1 } END { print s + 0 }'
}

# workload_clean <name> — remove anything a previous suite left in the corpus.
# Called before a corpus is measured, not just after it is used: an
# interrupted run leaves recovery sets behind, and the next run would then
# treat them as input.
workload_clean() {
    local dir parent base
    dir=$(workload_dir "$1")
    [[ -d $dir ]] || return 0

    # Inside the corpus: recovery sets, and par2cmdline's numbered pre-repair
    # backups (`file.bin.1`, `file.bin.2`, …). Both are outputs; leaving either
    # behind turns them into inputs for whatever runs next.
    #
    # `-type f` is load-bearing, not decoration: without it the numeric-suffix
    # pattern also matches the corpus directory itself, which is named after
    # the scale (`many-small@0.25`). No workload defines a file whose name ends
    # in a bare numeric extension, so nothing legitimate is at risk.
    find "$dir" -type f \( -name '*.par2' -o -regex '.*\.[0-9]+$' \) -delete

    # Beside the corpus, not inside it: `pesto --par2-only` given a directory
    # writes the recovery set one level *above* the release folder and names it
    # after the folder — see `par2_output_dir` in crates/pesto/src/poster/mod.rs,
    # which puts the set where the File Description packets' relative paths
    # resolve. So a `stages` run on `movie-1080p@0.25/` leaves
    # `bench/data/movie-1080p@0.25.par2` and its volumes behind, which the
    # sweep above cannot see. They never corrupt a measurement (nothing walks
    # the cache root as input) but they are hundreds of megabytes per run.
    parent=$(dirname "$dir")
    base=$(basename "$dir")
    find "$parent" -maxdepth 1 -type f \
        \( -name "$base.par2" -o -name "$base.vol*.par2" \) -delete
    return 0
}

# workload_root <name> — the path to hand a poster.
#
# The corpus directory is a container named after the workload and scale; the
# thing a poster should actually be given is the release folder inside it.
# Descends while the current directory holds exactly one entry and that entry
# is a directory, which unwraps `many-small@0.05/many-small/` down to the
# folder holding the files without touching a genuinely nested release like
# `mixed-folder@1.0/Benchmark.Movie…/` (which has files *and* subdirectories at
# its top level, so the descent stops there).
#
# This is not cosmetic: ngPost refuses to recurse into subdirectories without
# --compress, so handing it the container instead of the release folder makes
# it report an empty input and drop out of the comparison entirely.
workload_root() {
    local dir count only
    dir=$(workload_dir "$1")
    while :; do
        count=$(find "$dir" -mindepth 1 -maxdepth 1 ! -name '.manifest.jsonl' | wc -l)
        [[ $count -eq 1 ]] || break
        only=$(find "$dir" -mindepth 1 -maxdepth 1 ! -name '.manifest.jsonl')
        [[ -d $only ]] || break
        dir=$only
    done
    echo "$dir"
}

# workload_is_nested <name> — true when the posting root contains
# subdirectories, i.e. when a tool that cannot recurse will not see everything.
workload_is_nested() {
    local root
    root=$(workload_root "$1")
    [[ -n $(find "$root" -mindepth 1 -type d -print -quit) ]]
}

# workload_verify <name> — recompute every file's CRC-32 and compare with the
# manifest. Slow (it reads the whole corpus), so it is opt-in via
# `run.sh --verify-data`; without it, a corrupted or half-written corpus would
# silently produce results that cannot be reproduced anywhere else.
workload_verify() {
    local name=$1 dir manifest bad=0
    dir=$(workload_dir "$name")
    manifest="$dir/.manifest.jsonl"
    [[ -r $manifest ]] || { warn "no manifest for '$name'; nothing to verify"; return 1; }

    local line path want got
    while IFS= read -r line; do
        path=$(sed -n 's/.*"path":"\([^"]*\)".*/\1/p' <<< "$line")
        want=$(sed -n 's/.*"crc32":"\([^"]*\)".*/\1/p' <<< "$line")
        [[ -n $path && -n $want ]] || continue
        got=$("$BENCH_GEN_BIN" --check "$path" |
              sed -n 's/.*"crc32":"\([^"]*\)".*/\1/p')
        if [[ $got != "$want" ]]; then
            warn "corpus mismatch: $path (manifest $want, on disk $got)"
            bad=1
        fi
    done < "$manifest"

    (( bad )) && return 1
    info "$(green "corpus '$name' verified")"
    return 0
}

# describe_workload — one line for the run header and the report.
describe_workload() {
    workload_load "$1"
    local bytes
    bytes=$(workload_bytes "$1")
    printf '%-18s %10s  par2=%s%%  art=%s  %s\n' \
        "$WL_NAME" "$(human_bytes "$bytes")" "$WL_PAR2_PCT" \
        "$WL_ARTICLE_SIZE" "$WL_DESC"
}
