use crate::config;
use anyhow::{Context, Result};
use std::io::{self, Write};

/// Run the interactive setup wizard.
pub fn run() -> Result<()> {
    let path = config::default_config_path()
        .context("cannot locate a config directory: set $HOME or $XDG_CONFIG_HOME")?;

    println!("pesto setup — answer a few questions to create your config.");
    println!("Press Enter to accept the [default] shown in brackets.\n");

    if path.exists() {
        let overwrite = ask("Config already exists; overwrite it? (y/N)", "n")?;
        if !overwrite.eq_ignore_ascii_case("y") {
            println!("Aborted; existing config kept.");
            return Ok(());
        }
    }

    let host = ask_required("NNTP server hostname")?;
    let port = ask("Server port", "563")?;
    let ssl = ask("Use TLS? (Y/n)", "y")?;
    let ssl = !ssl.eq_ignore_ascii_case("n");
    let connections = ask("Parallel connections", "10")?;
    let username = ask("Username (blank for none)", "")?;
    let password = if username.is_empty() {
        String::new()
    } else {
        ask("Password", "")?
    };
    let groups = ask("Newsgroups (comma-separated)", "alt.binaries.test")?;
    let from = ask("From header (blank = random identity per run)", "")?;
    let par2 = ask("PAR2 recovery percentage (0 disables)", "10")?;

    let mut toml = String::new();
    toml.push_str("# pesto configuration — generated by `pesto --config`.\n\n");
    toml.push_str("[server]\n");
    toml.push_str(&format!("host = \"{}\"\n", esc(&host)));
    toml.push_str(&format!("port = {}\n", port.trim()));
    toml.push_str(&format!("ssl = {ssl}\n"));
    toml.push_str(&format!("connections = {}\n", connections.trim()));
    toml.push('\n');

    if !username.is_empty() {
        toml.push_str("[auth]\n");
        toml.push_str(&format!("username = \"{}\"\n", esc(&username)));
        toml.push_str(&format!("password = \"{}\"\n\n", esc(&password)));
    }

    toml.push_str("[posting]\n");
    let group_list = groups
        .split(',')
        .map(|g| format!("\"{}\"", esc(g.trim())))
        .collect::<Vec<_>>()
        .join(", ");
    toml.push_str(&format!("groups = [{group_list}]\n"));
    if from.is_empty() {
        toml.push_str("# from omitted: each run posts under a random identity.\n");
    } else {
        toml.push_str(&format!("from = \"{}\"\n", esc(&from)));
    }
    toml.push_str(&format!("par2 = {}\n", par2.trim()));

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating config directory `{}`", parent.display()))?;
    }
    std::fs::write(&path, toml)
        .with_context(|| format!("writing config file `{}`", path.display()))?;

    println!("\nWrote {}", path.display());
    println!("pesto will load it automatically. Post a file with: pesto <FILE>");
    Ok(())
}

fn ask(label: &str, default: &str) -> Result<String> {
    if default.is_empty() {
        print!("{label}: ");
    } else {
        print!("{label} [{default}]: ");
    }
    io::stdout().flush().ok();
    let mut line = String::new();
    io::stdin()
        .read_line(&mut line)
        .context("reading from stdin")?;
    let line = line.trim().to_string();
    Ok(if line.is_empty() {
        default.to_string()
    } else {
        line
    })
}

fn ask_required(label: &str) -> Result<String> {
    loop {
        let value = ask(label, "")?;
        if !value.is_empty() {
            return Ok(value);
        }
        println!("  (required — please enter a value)");
    }
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
